manifests/server/options.pp
spec/defines/dns__server__options_spec.rb
templates/named.conf.options.erb

I've added a `$listen_on_port` option to `dns::server::options` to allow the port to be customized.  Rspec tests included.

allow port to be customized in dns::server::options

---

manifests/record.pp
manifests/record/mx.pp
spec/defines/dns__record__mx_spec.rb
spec/defines/dns__record_spec.rb

Fixes ajjahn/puppet-dns#37
- adds all fields to alias: host, zone, pref, and data
- any three of the four can be the same for multiple MX records
under management, which would previously cause a duplicate alias
- add test to confirm concat fragment is named as expected
Fixes ajjahn/puppet-dns#39 by writing the promised tests
Other changes of note:
Default preference is now 10. A pref of 0 is allowed, but if a
DNS administrator wanted to insert a more-preferable MX record,
she would be unable to do so until the previous record TTL expired.
Default host is now '@'. This allows for cleaner manifests because
the most common MX case is to create an exchanger for the entire
$ORIGIN. BIND will do the substitution automatically.
Blank labels are permitted in zone files, but are not handled by …

MX preference fix, unique alias, add tests

---

manifests/server/options.pp

Using style guide at https://docs.puppetlabs.com/guides/style_guide.html#puppet-doc

cleanup of inline rdocs in `dns::server::options` class

---

spec/defines/dns__server__options_spec.rb

Change test to match the context description

Test check_names_response with wrong string

---

README.md

A simple change to the documentation, as described in https://github.com/ajjahn/puppet-dns/issues/79

Added a description to make RHEL/CentOS users aware that EPEL is required.

---

manifests/server/options.pp
spec/defines/dns__server__options_spec.rb
templates/named.conf.options.erb

Would you guys find this useful? It looked like existing allow-transfer feature was for the zone level only. We have some need for global allow-transfer, so I added this in. Based the unit tests on the forwarders tests.

Added in feature allowing for global allow-transfer

---

spec/defines/dns__server__options_spec.rb

The rake tests fail because of an invalid regexp on line 101 of `spec/defines/dns__server__options_spec.rb`.  I escaped the bare `{` in that regexp:
it { should contain_file('/etc/bind/named.conf.options').with_content(/allow-recursion \{$/) }

spec tests: fix invalid range in regexp

---

manifests/record/a.pp
manifests/record/aaaa.pp
manifests/record/cname.pp
manifests/record/mx.pp
manifests/record/ns.pp
manifests/record/ptr.pp
manifests/record/txt.pp
spec/defines/dns__record__aliases.spec.rb
spec/defines/dns__record__mx_spec.rb

I noticed that the current resource definitions in the `dns::record::`* classes all base their resource names on the zonefile host entry.  This means that you cannot create multiple entries of the same type for the same name.
Admittedly,most of the entries allow for an array for the data parameter, but there's one case where this doesn't work:  automatic ptr entry creation.
Suppose I want to create these DNS zones fragments:
foo     IN A    192.168.100.101
foo     IN A    192.168.100.102
...and...
101    IN PTR    foo.example.com.
102    IN PTR    foo.example.com.
Under the current code, I would not be able to use the automatic PTR record generation for this, because I would have to use a two-item array for the data of the A record, but the automatic PTR generation only looks at the first …

Use resource names instead of hosts for the aliases of dns record types.  With spec test file.

---

manifests/zone.pp
spec/defines/dns__zone_spec.rb

The `zone.pp` class should not be allowed to create or modify the zone file for a slave zone at all.  It should only manage master zone files.
I just added in a check to `zone.pp` so it only creates the `concat` type for master files, for all others it sets the `concat` to `ensure => absent`.

zone files should only be created or modified for master zones

---

.fixtures.yml
metadata.json

The build started failing after I merged in #99, but it was passing when I clicked the green button.
This is because the concat module has changed since then, and our fixtures are set to always build against master.
This PR adds file_concat as a dependent module, as apparently that is a thing now:
https://github.com/puppetlabs/puppetlabs-concat#what-concat-affects
At first I thought about just pinning our fixtures to released versions, which seems like a good short term fix. However it will blind us to real breaking changes, and also means we have to manually bump it all the time to test against new versions?
I'm up for alternatives. Obviously I want the built to pass. I'm surprised that concat has an external dependency now, especially a non-puppetlabs one? But if they depend on it, then …

Added file_concat as a dependent module

---

manifests/server/options.pp
manifests/zone.pp
spec/defines/dns__server__options_spec.rb
spec/defines/dns__zone_spec.rb
templates/named.conf.options.erb
templates/zone.erb

This pull request adds more complete notification options to both zones
and the server options.  In both cases, `zone_notify` sets the BIND
"notify" option (which can be one of *on*, *off*, *master-only*, or
*explicit*), and `also_notify` is a list of ip addresses of name servers
that will be sent notifications in addition to the zone's nameservers.
Both zone_notify and also_notify are validated in dns::server::options
and dns::zone, and new tests are added to dns__server__options_spec.rb
and dns__zone_spec.rb to test the individual values for each parameter.

Add notify to server options & also_notify to server and zone options.

---

manifests/server/params.pp
spec/classes/dns__server__install_spec.rb

Also add RedHat validation to `dns__server__install_spec.rb`

Remove dnssec-tools from RedHat package list.

---

manifests/server/config.pp
manifests/server/params.pp
spec/classes/dns__server__config_spec.rb
templates/named.conf.erb

This PR incorporates and fixes the changes proposed by chriscrowley
in PR https://github.com/ajjahn/puppet-dns/pull/102:
-   control content of named.conf in addition to simple presence and ownership.
-   add to server params the additional named.conf settings that differ between Debian and RedHat
-   use a single template for both OSes
-   add tests for RedHat and update tests for Debian to ensure that named.conf is getting created with proper ownership and content.

issue 101: take control of named.conf.

---

templates/named.conf.erb

Hi - Was unable to start the named service due to syntax error in named.conf tempate. This PR corrects the syntax on the comments.

Fix comment syntax in named.conf template

---

manifests/server/install.pp
manifests/server/params.pp
spec/classes/dns__server__install_spec.rb

Hi - With the environments I work with we need a bit more control of the versions of software installed and can't take the latest versions straight away. This PR is to have a parameter for the packages so that an alternative value such as 'present' can override the default value for the param. I set the default for the new param to 'latest' as that is what the module currently uses.

Add param to manage packages

---

manifests/zone.pp

There was extra dot in the $soa and $soa_email definition. The consequence was an extra dot in the zones/db.xxx file.

Fixes #93 - Avoid the extra dot in the soa

---

manifests/key.pp
manifests/server/config.pp
manifests/zone.pp
metadata.json

The concat module is on version 2.0.0. The vast majority of changes are internal, meant to speed the module up. On first glance there do not appear to be any changes which would cause this module issue.

Updated concat module version

---

templates/zone.erb

the zone template was including empty allow_transfer {} blocks because
a 0-length array was still being treated as "true".  this PR changes
the check to verify that @allow_transfer is an array and has >0 size.

fix zone template's @allow_transfer check

---

tests/init.pp

The tests/init.pp smoketest hardcoded the /etc/bind directory; this changes it to use ${dns::server::params::cfg_dir} instead so the smoketest will be valid on RedHat family systems.

Correct path for named.conf.options in tests/init.pp

---

manifests/zone.pp

The dns::zone class tried to reference dns::server::options::forwarder as if dns::server::options was a class rather than a defined type.  Removing that check for now.

Remove invalid reference to dns::server::options::forwarder

---

manifests/server/options.pp
manifests/server/params.pp
spec/defines/dns__server__options_spec.rb
templates/named.conf.options.erb

Default it to "absent" on RedHat 5 whose default bind package is too old for dnssec.

Make dnssec validation a configurable option.

---

manifests/server/options.pp
templates/named.conf.options.erb

Instead of hardcoding it to point to /var/cache/named (which does not exist on RedHat), use dns::server::params::data_dir instead.

Fix the `directory` option in named.conf.options

---

manifests/server/params.pp
templates/named.conf.erb

Three major big fixes which were introduced to the "named.conf" file in #112 - 
* Corrected the location of the rndc.key file on debian.
* Removed the extra definition of the "." zone.
* Removed the "logging" setup, which referred to a nonexistent file.
All three of these errors will prevent bind from starting up.
This should resolve #115.

Named.options fix

---

manifests/key.pp

Replaced the hardcoded package name with the package variable.

Fixed a bug where key did not work on redhat due to incorrect pkg name

---

Gemfile.lock

Here are the actual Gemfile.lock differences from the previous checked-in version:
-  `rspec-puppet` is moved from a git repo to a rubygems gem
-  The following gems are added:
-  rspec-puppet `2.2.0`
-  The following gems are removed:
-  The following gems have different versions:
-  CFProperyList - was `2.3.1` - is now `2.2.8`
-  facter - was `1.7.6` - is now `2.4.4`
-  fog-ecloud - was `0.1.1` - is now `0.1.2`
-  fog-profitbricks - was `0.0.2` - is now `0.0.3`
-  rspec - was `3.2.0` - is now `3.1.0`
-  rspec-core - was `3.2.3` - is now `3.1.7`
-  rspec-expectations - was `3.2.1` - is now `3.1.2`
-  rspec-mocks - was `3.2.1` - is now `3.1.3`
-  rspec-support - was `3.2.2` - is now `3.1.2`
-  signet - was `0.6.0` - is now `0.6.1`
-  specinfra - was `2.34.6` - is now `2.34.9`
-  The …

add updated Gemfile.lock

---

manifests/server/params.pp

hi i have excluded dnssec-tools for debian 8, there is no package in official repository for jessie.

params.pp: excluded dnssec-tools from $necessary_package for debian 8

---

manifests/zone.pp
spec/defines/dns__zone_spec.rb
templates/zone.erb

This just changes the `zone.erb` template to allow the `@slave_masters` parameter to be an array, in which case it gets joined by `";"` semicolons; if it's not an array, it's interpolated directly, just like the previous behavior.

Allow the dns::zone::slave_masters parameter to be an array

---

manifests/server/options.pp
spec/defines/dns__server__options_spec.rb
templates/named.conf.options.erb

Previously, the "listen-on-v6" option was hard-coded to the value "any" which limited IPv6 configurability.
This commit adds dns::server::options::listen_on_ipv6, allowing an array of values to be provided for the config option.

Make "listen-on-v6" a configurable option

---

templates/zone_record.erb

This PR fixes the warning:
```
Warning: Variable access via 'preference' is deprecated. Use '@preference' instead. template[/path/to/puppet/modules/dns/templates/zone_record.erb]:7
(at /usr/lib/ruby/vendor_ruby/puppet/parser/templatewrapper.rb:76:in `method_missing')
```

fix variable access preference with @preference

---

manifests/server/default.pp

When using puppet future parser, this module does not work when e.g. resolvconf is not set (read: undef).
```
Error: The resolvconf value is not type of a string yes / no. on node example.xyz
```
This PR fixes this. Maybe you should have travis test Puppet 4 and future parser as well. But I think, this is out of scope of this PR.

fixes for puppet future parser support

---

.fixtures.yml
.gitignore

Yea I think we would be better served using released versions of modules instead of HEAD on them.
I'll try to set that which should close #142

[WIP] Fix fixtures

---

manifests/server/options.pp
manifests/server/params.pp
spec/defines/dns__server__options_spec.rb
templates/named.conf.options.erb

Add boolean option to `dns::server::options` to control whether DNS-SEC support is enabled/disabled. Also including tests & docs for same.
This option is default to false on RedHat 5 due to lack of DNS-SEC support, and true on all other platforms.

Control whether DNS-SEC support is enabled/disabled

---

manifests/zone.pp
spec/defines/dns__zone_spec.rb
templates/zone.erb

Adds support for delegation-only zone types as specified on Pg. 105 of [Bind 9.10 Manual](https://www.isc.org/wp-content/uploads/2014/01/Bv910ARM.pdf). 
Added rspec test to ensure that a `dns::zone` with type `delegation-only` contains no other statements.

Add support for delegation-only zone types.

---

manifests/zone.pp
spec/defines/dns__zone_spec.rb
templates/zone.erb
tests/init.pp

adding a `allow-query` parameter to the zone define.

Allow query zone

---

manifests/server/default.pp
spec/classes/server/default_spec.rb

When trying to integrate this module with my puppet environment, it kept claiming that the named user wasn't present. This was because the package hadn't yet been installed.
Error: Could not set 'present' on ensure: Could not find user named at 46:/vagrant/puppet-control/modules/dns/manifests/server/default.pp
Error: Could not set 'present' on ensure: Could not find user named at 46:/vagrant/puppet-control/modules/dns/manifests/server/default.pp
Wrapped exception:
Could not find user named
Error: /Stage[main]/Dns::Server::Default/File[/etc/sysconfig/named]/ensure: change from absent to present failed: Could not set 'present' on ensure: Could not find user named at 46:/vagrant/puppet-control/modules/dns/manifests/server/default.pp
This change makes sure the the file doesn't get created …

Added Package require

---

manifests/record.pp

Current version casues this error when using any of the wrapper classes for records:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Comparison of: String >= Integer, is not possible. Caused by 'A String is not comparable to a non String'. at /etc/puppetlabs/code/environments/production/modules/dns/manifests/record.pp:24:34 at /etc/puppetlabs/code/environments/production/modules/dns/manifests/record/cname.pp:19 on node
This error is caused by future parser not liking the comparison of integer and string, stole a really simple fix from: https://github.com/jfryman/puppet-nginx/issues/684
Also of note I couldn't get the tests to run even on the master branch, gave me a "NameError: …

Comparison of: String >= Integer, is not possible

---

manifests/acl.pp
manifests/server/config.pp
manifests/zone.pp
metadata.json

The ensure parameter is deprecated for concat::fragment since [v2.0.0 of puppetlabs-concat](https://github.com/puppetlabs/puppetlabs-concat#ensure-1)
On systems with puppetlabs-concat v2.0.0 the ensure parameter is ignored for concat::fragment and it works just fine, so I removed the ensure settings.

Removed 'ensure' setting from concat::fragment statements

---

Gemfile.lock
manifests/zone.pp
spec/defines/dns__zone_spec.rb

This will reverse the components of the zone title in addition to
appending `.in-addr.arpa` to the end.
For example:
dns::zone { '10.23.45':
...
reverse => reverse
...
}
would result in a zone definition of:
zone "45.23.10.in-addr.arpa" {
...
file "db.10.23.45"
...
}

Add `reverse => reverse` option to dns::zone

---

.fixtures.yml
metadata.json

Remove unneeded dependency on electrical/file_concat module

---

templates/named.conf.options.erb

Delete tab symbols and correct indentation of template
Fragment config before fixed:
```
forwarders {
10.7.1.1;
10.7.1.2;
-    };
+};
listen-on {
10.7.99.1;
-    };
+};
listen-on-v6 { any; };
port 53;
allow-recursion {
-      localnet;
+       localnet;
};
allow-query {
-      localnet;
+       localnet;
};
```
Fragment config after fixed:
```
forwarders {
10.7.1.1;
10.7.1.2;
-};
+    };
listen-on {
10.7.99.1;
-};
+    };
listen-on-v6 { any; };
port 53;
allow-recursion {
-       localnet;
+      localnet;
};
allow-query {
-       localnet;
+      localnet;
};
```

Correct indentation of template.

---

manifests/record/txt.pp
spec/defines/dns__record__txt_spec.rb
templates/zone_record.erb

#170 This change modifies the `zone_record.erb` template so that it
processes the data values for TXT and SPF records to produce proper
DNS quoted strings (of no more than 255 characters, with embedded
quotes and backslashes escaped with backslashes).
It also adds SPEC tests for the TXT record type.

issue #170: Produce proper DNS quoted strings for TXT and SPF records

---

manifests/collector.pp
manifests/zone.pp

`dns::collector` should be collecting resources of type `Dns::Member`, not bare `Member`.
`dns::zone` had a call to `error()` which should have been `fail()`

Fix typos in `dns::collector` and `dns::zone`

---

README.md
manifests/zone.pp
spec/defines/dns__zone_spec.rb
templates/zone.erb

Allow dynamic dns, fixes ajjahn/puppet-dns#54

---

README.md
manifests/tsig.pp
spec/defines/dns__tsig_spec.rb
templates/tsig.erb

To exchange DNS zones between two bind installations like master/slave you can sign this transaction with a key. It's more secure as IP-based zone transfer and protect against spoofing (see ftp://ftp.isc.org/isc/bind/9.8.0-P4/doc/arm/Bv9ARM.ch04.html#tsig)

feature TSIG configuration

---

manifests/zone.pp

In previous installation serial number in zone file is usualy set to YYYYMMDDNN (i.e. 2016111401)  which is higher as the new auto-generated serial numer in unix-timestamp (i.e. 1479158503). For this reason I want to re-implement the optional parameter.

feat re-implement serial number in dns zone as optional parameter

---

manifests/record.pp
manifests/server/options.pp
manifests/zone.pp

The module default settings for data_dir is '/etc/bind/zones'. In Ubuntu
this is not possible without apparmor config adjustments, because by
default apparmor denies changes in this directory.
Therefore it should be possible to change the data_dir in this module.

Make data_dir configurable in defined resource types.

---

manifests/zone.pp
spec/defines/dns__zone_spec.rb
templates/zone.erb

This branch/PR adds support for the _stub_ [zone type](http://ftp.isc.org/isc/bind9/cur/9.9/doc/arm/Bv9ARM.ch06.html#zone_statement).

Add support for stub zones

---

manifests/tsig.pp

Currently the config_dir part of this was set to /etc/bind.   Changed to module variable config_dir for proper execution.

fixing path issue which prevents working when path is not /etc/bind

---

manifests/record/ptr/by_ip.pp
spec/defines/dns__record__ptr__by_ip_spec.rb

... to allow fully-qualified `host` values.
Also create basic spec tests for dns`dns::record::ptr::by_ip` type

`dns::record::ptr::by_ip`: Permit `zone` parameter to be empty

---

Rakefile

... instead of `%{linenumber}`.  puppet-lint 1.0.0 changed `%{linenumber}`
to `%{line}` for the log_format option.

Fix PuppetLint log_format configuration to use `%{line}`

---

manifests/server/options.pp
spec/defines/dns__server__options_spec.rb

... to fix the named.conf.options expansion.  Also
validate `data_dir` and `working_dir` as absolute paths,
and add `data_dir` and `working_dir` tests to the spec
test for `dns::server::options`.

Add `working_dir` parameter to `dns::server::options`

---

manifests/server/options.pp
spec/defines/dns__server__options_spec.rb
templates/named.conf.options.erb

Controlled by `dns::server::options` parameter `forward_policy`
Add `forward_policy` to spec tests

Add global `forward` policy to the `options` block

---

.fixtures.yml
Gemfile
metadata.json

Restrict puppetlabs-concat version to < 2.2.1
The puppetlabs-concat module version `2.2.1` (just released) introduces a breaking change for Puppet < `3.2.0`: it includes the use of `Puppet::Parameter::Boolean` for type checking, but those parameter types were not introduced until `3.2.0`.
----
Restrict puppetlabs_spec_helper gem version to < 2.1.1
puppetlabs_spec_helper gem version `2.1.1` introduces a dependency on the `parallel` gem, which requires Ruby 2.0.  This breaks all testing on older Ruby versions.

Fix breaking tests on old puppet and ruby

---

manifests/server/options.pp
templates/named.conf.options.erb

In the same way that it is configure a statistic channel, this commit
adds control_channel_ip, control_channel_port y control_channel_allow to
configure a control channel

Add supports to configure control channel

---

manifests/server/options.pp
templates/named.conf.options.erb

The query_log_enable makes a predefined configuration. This commit adds
log_channels and log_categories so you could make a more fine
configuration.

Add parameters to configure bind logging

---

manifests/server/options.pp
templates/named.conf.options.erb

So you can use more options than the explicitily defined

Add extra_options parameter to bind::server::options

---

files/named.conf.default-zones
manifests/server.pp
manifests/server/config.pp
manifests/server/view.pp
manifests/zone.pp
templates/named.conf.erb
templates/view.erb

Add `dns::server::view` to configure dns views.
In order to handle this, I have also modified a little the zone implementation to be able to use a file different than _named.conf.local_ to include the zone configurations.
It also adds a `enable_default_zones` to `dns::server` so the inclussion of the `named.conf.default-zones` file could be ommited when views are used (in this case all zones must be defined inside a view, so that file could not be globally included).

Add dns::server::view

---

Gemfile
manifests/record/ptr/by_ip.pp
spec/defines/dns__record__ptr__by_ip_spec.rb

In DNS zone files, a host of `@` means the value of `$ORIGIN`, which, for zones configured by this module, means the `$zone` parameter.  This change makes the `dns::record::ptr::by_ip` type catch the `@` name and use the zone if possible.
_Note_ - this is based off of the `jearls_find_rspec_puppet_version_that_works` branch, to ensure the `spec` tests work.
Fixes #226

Use zone for PTR record with host of `@`

---

Gemfile

The `rspec-puppet` gem update to version `2.6.0` broke things for Puppet 3.0 - 3.5.  Until this gets fixed (I've got a PR into the `rspec-puppet` github repo for the fix), this change will limit `rspec-puppet` to earlier than `2.6.0`.

Find a version of rspec-puppet that works with older puppets

---

manifests/key.pp
manifests/tsig.pp
metadata.json
spec/defines/dns__key_spec.rb

Last versions of concat module have removed the ensure parameter for
concat::fragment (deprecated since v2.0.0).

Fix concat::fragment usage.

---

manifests/server/params.pp

ae6cfc5 already introduced this, but only for debian 8 (jessie). This
patch applies the same thing to debian 9 (stretch) and also all later
versions. The check condition just changed from '==8' to '>=8'.

params.pp: exclude dnssec-tools from $necessary_packages for debian >= 8

---

manifests/record.pp

I'm unsure if it's a Puppet version thing, but this line was giving me the following error:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Left match operand must result in a String value. Got an Integer. at /modules/dns/manifests/record.pp:19:6 at /modules/dns/manifests/record/a.pp:17 on node puppetmaster
Forcing the match operand to a string fixed it for me.

Fix "left match operand must be string" error

---

manifests/server/config.pp
templates/named.conf.default-zones.erb

Instead a fixing configuration path, it uses now module variables.
This patch fixes #235

Fix static path in named.conf.default-zones

---

manifests/server/params.pp
manifests/zone.pp
spec/classes/dns__server__install_spec.rb
spec/classes/server/default_spec.rb
spec/defines/dns__zone_spec.rb
templates/zone_file.erb

These changes validate all zone files with named-checkzone before putting the new zone file in or restarting BIND. I was having a lot of trouble with making mistakes in my records leading to my DNS servers crashing, this should prevent that.
Tested in CentOS 7 and Ubuntu Xenial as working, though I'm not familiar enough with Rspec to write a test for it unfortunately.

Check zones before using them
